### ISSUE TITLE
Doesn't start using `cdl` command on Linux

### ISSUE THREAD

**Issue by coutouly** [DataLab-Platform/DataLab#97]
**Describe the bug**
after a pip install doesn't start

**To Reproduce**
pip install cdl
cdl --verbose debug
[1]    1424050 segmentation fault (core dumped)  bin/cdl --verbose debug

**Expected behavior**

start

**Screenshots**

**Installation information**

pip list
Package                   Version
------------------------- -----------
annotated-types           0.7.0
asttokens                 2.2.1
attrs                     24.2.0
cachetools                5.5.0
cdl                       0.17.0
certifi                   2024.8.30
charset-normalizer        3.3.2
comm                      0.2.2
configparser              7.1.0
contourpy                 1.3.0
cycler                    0.12.1
datalab                   1.1.4
debugpy                   1.8.5
decorator                 5.1.1
executing                 2.1.0
fonttools                 4.53.1
future                    1.0.0
google-api-core           2.19.2
google-api-python-client  2.143.0
google-auth               2.34.0
google-auth-httplib2      0.2.0
google-cloud              0.34.0
googleapis-common-protos  1.65.0
guidata                   3.6.2
h5py                      3.11.0
htmlmin                   0.1.12
httplib2                  0.22.0
idna                      3.8
ImageHash                 4.3.1
imageio                   2.35.1
ipykernel                 6.29.5
ipython                   8.27.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.1.1
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.2
jupyter_core              5.7.2
kiwisolver                1.4.7
lazy_loader               0.4
MarkupSafe                2.1.5
matplotlib                3.9.2
matplotlib-inline         0.1.7
missingno                 0.5.2
mock                      5.1.0
multimethod               1.12
nest-asyncio              1.6.0
networkx                  3.3
numpy                     1.26.4
oauth2client              4.1.3
opencv-python-headless    4.10.0.84
packaging                 24.1
pandas                    2.2.2
pandas-profiling          3.2.0
parso                     0.8.4
pexpect                   4.9.0
phik                      0.12.4
pillow                    10.4.0
pip                       24.2
platformdirs              4.2.2
plotly                    5.24.0
PlotPy                    2.6.2
prompt_toolkit            3.0.47
proto-plus                1.24.0
protobuf                  5.28.0
psutil                    6.0.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pydantic                  2.8.2
pydantic_core             2.20.1
Pygments                  2.18.0
pyparsing                 3.1.4
PyQt6                     6.7.1
PyQt6-Qt6                 6.7.2
PyQt6_sip                 13.8.0
python-dateutil           2.9.0.post0
PythonQwt                 0.12.7
pytz                      2024.1
PyWavelets                1.7.0
PyYAML                    6.0.2
pyzmq                     26.2.0
QtPy                      2.4.1
referencing               0.35.1
requests                  2.32.3
rpds-py                   0.20.0
rsa                       4.9
scikit-image              0.24.0
scikit-learn              1.3.2
scipy                     1.14.1
seaborn                   0.13.2
six                       1.16.0
stack-data                0.6.3
tangled-up-in-unicode     0.2.0
tenacity                  9.0.0
threadpoolctl             3.5.0
tifffile                  2024.8.30
tomli                     2.0.1
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
typing_extensions         4.12.2
tzdata                    2024.1
uritemplate               4.1.1
urllib3                   2.2.2
visions                   0.7.4
wcwidth                   0.2.13

**Additional context**

**Comment by PierreRaybaut** [comment]
Thanks for the feedback.

Could you please tell us more about your platform?

- OS family
- OS version
- Python version

**Comment by coutouly** [comment]
it seems like i have to manuelly add pip install pyqt5
it was not inside pip install cdl

**Comment by PierreRaybaut** [comment]
Actually, [as mentioned in the documentation](https://datalab-platform.com/en/intro/installation.html#package-manager-pip), you may install Qt together with DataLab using ``pip install cdl[qt]``.
